### ISSUE TITLE
Shaders not including station menus, or flanking screens?

### ISSUE THREAD

**Issue by AMoonRabbit** [psychicEgg/EDHM#15]
Hello,

I have performed a clean install of the EDHM_UI app, and in turn that has deployed v1.41 of the shaders mod to my install directory. As such the below is my current config:
![image](https://user-images.githubusercontent.com/3766988/104847400-a8e93200-58d7-11eb-9298-84fa30f95333.png)
Which results in the below:
![Screenshot_0108](https://user-images.githubusercontent.com/3766988/104847375-7f300b00-58d7-11eb-973b-b5194e6d96c0.jpg)
Please note the Speeding warning, and the left MFD are mostly unaffected. Station menus are included in this, as well as all other MFDs. Is this correct or should they be affected as well? I compared my setup with the broken shaders example images and all seems to be okay in that respect.
![Screenshot_0109](https://user-images.githubusercontent.com/3766988/104847376-80613800-58d7-11eb-99b3-e92cdfb5f582.jpg)

**Comment by alterNERDtive** [comment]
That is correct and at least mostly intended.

**Comment by psychicEgg** [comment]
Hiya, I haven’t modded any of the panels yet. They’ll take a long time so I’ll wait to see if the mod survives the Odyssey update before diving into it. Just checking, that’s what you’re referring to?

As for the ‘speeding’ indicator, several CMDRs asked me to leave it orange as it’s like a medium-level warning colour, so that’s why it’s still orange!

If I’ve misread your question just let me know

**Comment by AMoonRabbit** [comment]
Thank you both for the responses. Just wanted to confirm its by design and that I wasn't have issues with shaders elsewhere. No issues here then.
