### ISSUE TITLE
RSHIFT key doesn't work

### ISSUE THREAD

**Issue by TIMON72** [psychicEgg/EDHM#16]
For some reason the RSHIFT does not work, but the RCTRL works. For example, I'm trying to do the following:
```
; Cycle through the cabin lighting colors with CTRL F6
; Note: back = ALT F6 = reverse direction of the cycle
[keyToggleChooseLightingColour]
Key = rshift NUMPAD1 ; doesn't work
Back = rctrl NUMPAD1 ; works
type = cycle
x103 = 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,199
```
But for non-numeric values, RSHIFT works:
```
; Dim the HUD with F5
; Each press of F5 dims the HUD by 20% (5 is maximum, 0 is off)
[keyToggleHUDDimmer]
Key = rshift SUBTRACT ; works
Back = rctrl SUBTRACT ; works
type = cycle
y100 = 5,4,3,2,1,0
```
Sometimes the opposite happens:
```
; Toggle between standard panel opacity and increased opacity with F1
[keyTogglePanelOpacity]
Key = rshift DIVIDE ; works
Back = rctrl DIVIDE ; doesn't work
type = toggle
x111 = 1.5
```

**Comment by BlueMystical** [comment]
I also noticed that the 'Kill Switch' associated to SHIFT+F1 does not work.

**Comment by psychicEgg** [comment]
> For some reason the RSHIFT does not work, but the RCTRL works. For example, I'm trying to do the following:

@TIMON72 good catch! 

The reason RSHIFT (or LSHIFT, or SHIFT) doesn't work with the NUMPAD keys is because pressing SHIFT causes the numlock key to temporarily deactivate (even though the light stays on). 

So 3Dmigoto is interpreting the key presses on the NUMPAD as though the Numlock key is off. You can try it yourself .. open a text editor and insert 10 lines of text. While pressing SHIFT you can navigate your cursor with NUMPAD8,4,6,2 etc

I'll add a note about SHIFT NUMPAD into the profile tool.

> ; Toggle between standard panel opacity and increased opacity with F1

If you look inside that code block you will see "type = toggle", which means the 'key' simply switches between two values. 

I don't think 3Dmigoto accepts a 'Back' key designation when "type = toggle" (as it wouldn't do anything extra, since it is only a toggle between two values). I hope that makes sense!

rctrl DIVIDE will work if it's set as: Key = rctrl DIVIDE

----------------------------------------------------------------
@BlueMystical 

> I also noticed that the 'Kill Switch' associated to SHIFT+F1 does not work.

I just tested 1.41 from my Github and the Kill Switch is working correctly .. SHIFT F1 activates the kill switch.

However, your UI app is setting the x100 value incorrectly in KeyBinds.ini

It should be:
[keyToggleKillSwitch]
Key = shift F1
type = toggle
x100 = 0

not "x100 =1"

**Comment by TIMON72** [comment]
@psychicEgg I see, I will know from now on

**Comment by BlueMystical** [comment]
@psychicEgg :  Will be fixed in the next update.
