### ISSUE TITLE
Graphics settings are making the game chug + Shield color numbers seem wrong

### ISSUE THREAD

**Issue by ghost** [psychicEgg/EDHM#3]
I read through all the docs on this and set all my graphics settings according to what you recommended.
(Typically I use EDFX + Reshade, but did not during my test)

Everything initially ran smoothly. I rotated through and got the colors I wanted.
(Though I have to point out that I think the number-to-color mapping listed in the comments for the shield is incorrect)
After I closed and reopened the game to ensure my defaults were set correctly via the ini file, the game ran like garbage on my 1070TI which usually runs stock ULTRA with no problems.

So I uninstalled using the uninstall.bat file. After I did, I reopened Elite Dangerous and it still ran like crap until I swapped my settings back to the default ULTRA

What I think is happening is that something is setting something in the graphics settings that is causing this. It sounds like a lot of people are going through this so I figured I'd drop you a note to explain my experience that you might be able to use to find out what's causing it.

**Comment by psychicEgg** [comment]
Yeah I think some people's systems aren't compatible with the modding software 3dmigoto, not sure why as I didn't write the software. I run 4K ultra and don't have any issues, same with the guys who beta test for me. It's really hard to pin down because it could be anything causing a conflict .. usually it's an overlay of some sort so they should all be turned off. 

But I had some adware called Wondershare somehow install itself a few weeks ago, and I was getting stutters in-game with and without the mod until I wiped it off. All I can recommend is that you check task manager and close all running processes that you don't need, and make sure your video drivers are up to date. Also exclude the elite-dangerous-64 folder from virus checkers as they can slow it down too, since 3dmigoto is hooking into the shader processes.

Which number-to-colour mapping on the shield do you think is incorrect? I just double-checked them now and they match the description in the ini

**Comment by BlueMystical** [comment]
I run ED on an old **AMD Radeon HD 7700** GPU, yeah it's quite old, but i can run ED on Max settings without issues.
If his game still runs bad after uninstalling the mod, the reason may be elsewhere, perhaps some bloatware? 

Press [Windows] + [R] and type **msconfig** hit [ENTER], then look under '**Services**', Hide anything from Microsoft and look for anything suspicious, it is safe to uncheck non-microsoft stuff from there, re-boot and try the game again.
