### ISSUE TITLE
Xbox Controllers not working with Epic Version

### ISSUE THREAD

**Issue by joshoram80** [psychicEgg/EDHM#8]
I'm having the same problem as the Steam users who cannot use an Xbox controller with the mod, but none of the fixes apply as there is no Steam overlay obviously.

**Comment by psychicEgg** [comment]
Sorry I don't have the Epic version installed, but thanks for letting me know. When I've finished the beta for v1.4 of EDHM I'll install the Epic version and check the performance

Just to confirm, you don't have Steam running in the system tray? (sometimes it loads at startup)
Are there any options in the Epic launcher for managing controllers?

**Comment by joshoram80** [comment]
No Steam running in the tray at all. Epic Launcher is pretty bare bones. I am using DS4Windows and a Dual Shock controller so I'm not sure if it's some interaction between them that is causing it. EDHM was working at some points when i was testing it, but sometimes it wasn't so it's hard to say exactly why it was playing up.

**Comment by BlueMystical** [comment]
Just to let you know that im running both Steam and Epic Games Versions on the same PC and have absolutely no problems..... when i play ED, im kinda into other games at the moment.
Only thing that i use Keyboard + Mouse instead of Controller.

Your problem must be at the Keybindings i believe, either at ED's keybindings or the Mod's keybindings.
Try editing the Mod's INI file to set the keybindings to... to.... mmm...  a button from the controller?    
mmmm, idk if that would be possible bro.

and even if it is... you will loose several buttons of your controller that could be used at better things than switching your hud color, unless you really like switching your hud colors every 30 seconds or so, but i doubt so.
